version: 2.1

workflows:
  version: 2.1
  pipeline:
    jobs:
      - build
      - push_to_gcs_dev:
          context: gcp-storage-parizot
          requires: [ 'build' ]
      
      - hold:
          type: 'approval'
          requires: [ 'push_to_gcs_dev' ]
      
      - push_to_gcs_prod:
          context: gcp-storage-parizot
          requires: ['hold']

jobs:
  build:
    docker:
      - image: circleci/node:10.16.0-browsers
    working_directory: '~/project'
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run build -- --configuration=dev --output-path=dist/dev --progress=false
      - run: npm run build -- --configuration=production --output-path=dist/prod --progress=false
      - persist_to_workspace:
          root: '~/project'
          paths:
            - dist/dev
            - dist/prod

  push_to_gcs_dev:
    docker:
      - image: google/cloud-sdk
    steps:
      - attach_workspace:
          at: ~/project
      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - run: find . -type f -follow -print
      - run: gsutil rm -r gs://dev.evan.parizot.info/**
      - run: gsutil -m cp -r dist/dev/** gs://dev.evan.parizot.info/

  push_to_gcs_prod:
    docker:
      - image: google/cloud-sdk
    steps:
      - attach_workspace:
          at: ~/project
      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - run: find . -type f -follow -print
      - run: gsutil -m cp -r dist/prod/** gs://evan.parizot.info/
